### PR TITLE
Add tag for BTCPool

### PR DESCRIPTION
**Pull request by guybrushino**
https://mempool.space/it/block/00000000000000000001e6d039551b4a687434a5b05be4c1fa6a9faa33baade4

### CODE REVIEW

**Comment by 0xB10C** [comment]
Is there only this one block with the BTC-POOL tag? The existing BTCPool tag seemed related to the default tag of btc.com's old mining pool software: https://github.com/btccom/btcpool-ABANDONED/blob/0127a750b3b26a515e66261cbd9ad7f95c54de01/src/jobmaker/jobmaker.cfg#L20. This tag is different and I don't think they belong to the same entity.

**Comment by guybrushino** [comment]
I see these:
image

**Comment by 0xB10C** [comment]
Alright, so might make sense to add it as new entity? Or did the old "BTCPool" blocks stop when this one appeared?

**Comment by guybrushino** [comment]
I'll look into it and let you know

**Review by mazk69-dev — APPROVED** [review]
N/A

**Pull request closed without merging**
