### PR TITLE
Split-up pools.json file into multiple

### LINKED ISSUE #38: Change JSON scheme: Tag and address maps to list of pools
I've been thinking about changing the JSON schema.

Currently, pools.json contains two maps. One for mapping tags to pools and one for mapping addresses to pools. 

```json
{
   "coinbase_tags" : {
       "/pool a tag/": {
           "name": "Pool A",
           "link": "website pool a"
       },
   },
   "payout_addresses" : {
       "1Ea8eoaAddrToPoolASeryj3AXd3swuJ": {
           "name": "Pool A",
           "link": "website pool a"
       },
}
```

This results in a lot of duplicate data and has been an error source (e.g. "BitcoinIndia" vs. "Bitcoin India" as seen in #36).

I propose to have a single list of pool objects which each have a list of tags and addresses.

```json
[
    {
       "name": "Pool A",
       "link": "website pool a",
       "tags": [
         "/pool a tag/",
       ],
       "addresses": [
          "1Ea8eoaAddrToPoolASeryj3AXd3swuJ",
       ],
    }
]
```

The goal is to make this more maintainable and reduce the error surface.

The old schema could still be automatically generated from the new schema.

### PR DESCRIPTION
**Pull request by 0xB10C**
This splits out the large `pool.json` file into a more maintainable set of entities. One JSON file per pool. Backwards compatibility is provided with the added script `contrib/create-old-pools-json.py`.

Other formats, as discussed in e.g. https://github.com/0xB10C/known-mining-pools/issues/38#issuecomment-845819260 can be added later if needed.

The new format also allows for easier merging with other pool.json files from forks (btccom and blockchain-info).

Closes #38

### CODE REVIEW

**Comment by 0xB10C** [comment]
Python scripts mentioned in the commit messages:

```python
# to-entities.py
# converts pool.json to the file-per-pool structure

import json

names = dict()

with open("pools.json", "r") as f:
    pools = json.load(f)

    for tag in pools["coinbase_tags"]:
        e = pools["coinbase_tags"][tag]
        name = e["name"]
        link = e["link"]
        if name not in names:
            names[e["name"]] = { "links": set(), "addresses": set(), "tags": set() }
        if link != "":
            names[name]["links"].add(link)
        names[name]["tags"].add(tag)

    for addr in pools["payout_addresses"]:
        e = pools["payout_addresses"][addr]
        name = e["name"]
        link = e["link"]
        if name not in names:
            names[name] = { "links": set(), "addresses": set(), "tags": set() }
        if link != "":
            names[name]["links"].add(link)
        names[name]["addresses"].add(addr)

for name in names:
    filename = name.rstrip('.').replace("'", "").replace(" ", "-").replace(".", "-").replace("/", "").replace("&", "").replace("(", "").replace(")", "").lower()
    pool = names[name]

    content = {
        "name": name,
        "addresses": list(pool["addresses"]),
        "tags": list(pool["tags"]),
        "links": list(pool["links"]),
    }

    with open("entities/"+filename+".json", "w") as out:
        json.dump(content, out, indent=2, ensure_ascii=False)

```

```python
# sort-pools-json.py
# sorts the addresses and tags in pool.json file to make the files comparable
import json

names = dict()

with open("pools.json", "r") as f:
    pools = json.load(f)

    tags = pools["coinbase_tags"]
    addresses = pools["payout_addresses"]

    tags = dict(sorted(tags.items()))
    addresses = dict(sorted(addresses.items()))

    with open("pools-sorted.json", "w") as out:
        content = {
            "payout_addresses": addresses,
            "coinbase_tags": tags
        }
        json.dump(content, out, indent=2, ensure_ascii=False)

```

**Comment by Sjors** [comment]
ForkMonitor was fetching this file…

**Comment by 0xB10C** [comment]
Sorry, wasn't aware. Guess the symlink to [generated/pools.json](https://github.com/0xB10C/known-mining-pools/blob/master/generated/pools.json) doesn't work for fetching this file..

**Comment by Sjors** [comment]
It might work if I had fetched it locally, but I was fetching the file from Github.

**Pull request merged**
